train_dataset: ???
validation_dataset: ???

training_ds:
  dataset:
    _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
    manifest_filepath: ${train_dataset}
    max_duration: null
    min_duration: 0.75
    n_segments: 8192
    trim: false
  dataloader_params:
    drop_last: false
    shuffle: true
    batch_size: 16
    num_workers: 4

validation_ds:
  dataset:
    _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
    manifest_filepath: ${validation_dataset}
    max_duration: null
    min_duration: null
    n_segments: -1
    trim: false
  dataloader_params:
    drop_last: false
    shuffle: false
    batch_size: 16
    num_workers: 1

model:
  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    dither: 0.0
    frame_splicing: 1
    nfilt: 80
    highfreq: 8000
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: 1024
    n_window_size: 1024
    n_window_stride: 256
    normalize: null
    pad_to: 0
    pad_value: -11.52
    preemph: null
    sample_rate: 22050
    window: hann
    use_grads: false
    exact_pad: true

  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    resblock: 1
    upsample_rates: [8,8,2,2]
    upsample_kernel_sizes: [16,16,4,4]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]

  optim:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas: [0.8, 0.99]

  sched:
    name: CosineAnnealing
    min_lr: 1e-5
    warmup_ratio: 0.02

  max_steps: ${trainer.max_steps}
  l1_loss_factor: 45
  denoise_strength: 0.0025

trainer:
  max_steps: 25000